version: '3'

services:
  app:
    build: .
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - backend
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
    - .:/var/www
    networks:
      - backend
    ports:
      - 8081:8081
  database:
    env_file:
      - database-docker.env
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
networks:
  backend:
    driver: bridge
volumes:
  dbdata:
